class SHAREModules:
	"""
	SHARE modules, information taken from SHARE website
	"""
	modules_w8 = {'CV':'CV - Coverscreen', 
	'DN': 'DN - Demographics', 
	'PH': 'PH - Physical Health', 
	'BR': 'BR - Behavioural Risks', 
	'CF': 'CF - Cognitive Function',
	'MH':'MH - Mental Health', 
	'HC': 'HC - Health Care', 
	'EP': 'EP -Employment and Pensions', 
	'GS': 'GS - Grip Strength', 
	'WS': 'WS - Walking Speed',
	'CH': 'CH - Children',
	'SP': 'SP - Social Support', 
	'FT':'FT - Financial Transfers', 
	'HO': 'HO - Housing', 
	'HH': 'HH - Household Income', 
	'CO': 'CO - Consumption', 
	'AS': 'AS - Assets', 
	'AC': 'AC - Activities', 
	'EX': 'EX - Expectations', 
	'IV': 'IV - Interviewer Observations', 
	'SN': 'SN - Social Networks', 
	'AX': 'AX - Accelorometry', 
	'SR': 'SR - Savings Regret', 
	'TE': 'TE - Time Expenditure', 
	'CM': 'MC - Mini Childhood', 
	'IT': 'IT - IT module', 
	'XT': 'XT - End-of-Life Interview', 
	'LI': 'LI - Linkage', 
	'PF': 'PF - Peak Flow', 
	'BS': 'BS - Blood Sample', 
	'CS': 'CS - Chair Stand'}

	modules_w7 = {
	'RC': 'RC - Retrospective Children History',
	'RP': 'RP - Retrospective Partner History',
	'RA': 'RA - Retrospective Accomodation',
	'CC': 'CC - Childhood Circumstances',
	'RE': 'RE - Retrospective Employment',
	'FS': 'FS - Financial Section',
	'HS': 'HS - Health Section',
	'RH': 'RH - Retrospective Health Care',
	'GL': 'GL - General Life and Persecution',
	'CV':'CV - Coverscreen', 
	'DN': 'DN - Demographics', 
	'PH': 'PH - Physical Health', 
	'BR': 'BR - Behavioural Risks', 
	'CF': 'CF - Cognitive Function',
	'MH':'MH - Mental Health', 
	'HC': 'HC - Health Care', 
	'EP': 'EP -Employment and Pensions', 
	'GS': 'GS - Grip Strength', 
	'WS': 'WS - Walking Speed',
	'CH': 'CH - Children',
	'SP': 'SP - Social Support', 
	'FT':'FT - Financial Transfers', 
	'HO': 'HO - Housing', 
	'HH': 'HH - Household Income', 
	'CO': 'CO - Consumption', 
	'AS': 'AS - Assets', 
	'AC': 'AC - Activities', 
	'EX': 'EX - Expectations', 
	'IV': 'IV - Interviewer Observations', 
	'SN': 'SN - Social Networks', 
	'AX': 'AX - Accelorometry', 
	'SR': 'SR - Savings Regret', 
	'TE': 'TE - Time Expenditure', 
	'CM': 'MC - Mini Childhood', 
	'IT': 'IT - IT module', 
	'XT': 'XT - End-of-Life Interview', 
	'LI': 'LI - Linkage', 
	'PF': 'PF - Peak Flow', 
	'BS': 'BS - Blood Sample', 
	'CS': 'CS - Chair Stand'}

	
	


